/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    application
    kotlin("jvm") version "1.3.40"
    // application()
}

application {
    mainClassName = "library.ServerKt"
}

repositories {
    mavenCentral()
}


dependencies {
    implementation(kotlin("stdlib-jdk8"))
    compile("com.sparkjava:spark-core:2.8.0") // add to build.gradle (for Kotlin users)
    compile("com.google.code.gson:gson:2.8.5")
    compile("com.microsoft.sqlserver:mssql-jdbc:7.2.1.jre8")
}


// // https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
// testCompile group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '7.3.1.jre8-preview'
